version: 2
jobs:
  build:
    machine:
      environment:
        ANDROID_HOME: /usr/local/android-sdk-linux  
    general:
      artifacts:
          - /home/ubuntu/tapp/app/build/outputs/apk/
    test:
      override:
          # start the build
          - (./gradlew assemble):
              timeout: 360
          # start the emulator
          - emulator -avd circleci-android22 -no-audio -no-window:
              background: true
              parallel: true
          # wait for it to have booted
          - circle-android wait-for-boot
          # unlock the emulator screen
          - sleep 30
          - adb shell input keyevent 82
          # run tests  against the emulator.
          - ./gradlew connectedDevelopmentDebugAndroidTest -PdisablePreDex
          # copy the build outputs to artifacts
          - cp -r app/build/outputs $CIRCLE_ARTIFACTS
          # copy the test results to the test results directory.
          - cp -r app/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS

    steps: 
      - checkout
      - run:
          name: "Start the build"
          command: "./gradlew assemble"
      - run:
          name: "CodeCov"
          command: "bash <(curl -s https://codecov.io/bash)"