package com.testableapp;

import com.testableapp.activities.LoginActivity;
import com.testableapp.presenters.LoginPresenter;
import com.testableapp.views.LoginView;

import org.junit.Before;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.MockitoAnnotations.initMocks;
/**
 * In earlier versions of AGP (Android Privacy Guard) Robolectric you must specify the constants
 * field which points to the BuildConfig.class generated by the build system. Robolectric uses the constants
 * in the class to compute the output paths used by Gradle when building your project. Without these values,
 * Robolectric will not be able to find your merged manifest, resources, or assets.
 * This will cease to work in the future so we strongly recomend migrating to the new API.
 */
public class AbstractActivityTest {


    @InjectMocks
    final LoginActivity mActivity = new LoginActivity();

    @Mock
    LoginPresenter mPresenter;

    @Before
    public void setUp() throws Exception {
        initMocks(this);
    }

    @Test
    public void testCreation() {
        // Verify view has never been attached
        verify(mPresenter, never()).attachView(mActivity);

        // Attach the view
        mActivity.onAttachedToWindow();

        // Verify the presenter has been notified about the view's attachment
        verify(mPresenter, Mockito.times(1)).attachView(any(LoginView.class));
    }

    @Test
    public void testDestruction() {
        // Verify view has never been detached
        verify(mPresenter, never()).detachView();

        // Detach the view
        mActivity.onDetachedFromWindow();

        // Verify the presenter has been notified about the view's detachment
        verify(mPresenter, Mockito.times(1)).detachView();
    }
}
